# This rule is not used by the project hashirama itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to batch.starknet.l3 resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: hashirama
    app.kubernetes.io/managed-by: kustomize
  name: madarachain-viewer-role
rules:
- apiGroups:
  - batch.starknet.l3
  resources:
  - madarachains
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch.starknet.l3
  resources:
  - madarachains/status
  verbs:
  - get
