# This rule is not used by the project hashirama itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over batch.starknet.l3.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: hashirama
    app.kubernetes.io/managed-by: kustomize
  name: madarachain-admin-role
rules:
- apiGroups:
  - batch.starknet.l3
  resources:
  - madarachains
  verbs:
  - '*'
- apiGroups:
  - batch.starknet.l3
  resources:
  - madarachains/status
  verbs:
  - get
